"""Tests for Wyze camera RTSP stream_source support."""

from types import SimpleNamespace

import pytest

from custom_components.wyzeapi.camera import WyzeCamera
from custom_components.wyzeapi.const import (
    CONF_CAMERAS,
    CONF_RTSP_ENABLED,
    CONF_RTSP_PASSWORD,
    CONF_RTSP_SECURE,
    CONF_RTSP_USERNAME,
)


@pytest.fixture
def camera() -> SimpleNamespace:
    """Return a representative camera device."""
    return SimpleNamespace(
        mac="AA:BB:CC:DD:EE:FF",
        nickname="Driveway Cam",
        product_model="WYZE_CAKP2JFUS",
        device_params={"ip": "10.0.3.184"},
    )


@pytest.fixture
def config_entry() -> SimpleNamespace:
    """Return a config entry with no per-camera RTSP options configured."""
    return SimpleNamespace(options={})


@pytest.fixture
def entity(camera: SimpleNamespace, config_entry: SimpleNamespace) -> WyzeCamera:
    """Return a camera entity wired to the given camera and config entry."""
    return WyzeCamera(SimpleNamespace(), camera, config_entry)


def _config_entry_with_rtsp(
    mac: str,
    *,
    enabled: bool = True,
    username: str = "wyze",
    password: str = "hunter2",
    secure: bool = False,
) -> SimpleNamespace:
    """Return a config entry with one camera's RTSP options set."""
    return SimpleNamespace(
        options={
            CONF_CAMERAS: {
                mac: {
                    CONF_RTSP_ENABLED: enabled,
                    CONF_RTSP_USERNAME: username,
                    CONF_RTSP_PASSWORD: password,
                    CONF_RTSP_SECURE: secure,
                }
            }
        }
    )


@pytest.mark.asyncio
async def test_stream_source_is_none_when_rtsp_not_configured(
    entity: WyzeCamera,
) -> None:
    """No stream source is offered until RTSP is set up for this camera."""
    assert await entity.stream_source() is None


@pytest.mark.asyncio
async def test_stream_source_is_none_when_rtsp_disabled_for_this_camera(
    camera: SimpleNamespace,
) -> None:
    """A camera entry with rtsp_enabled=False is treated as not configured."""
    config_entry = _config_entry_with_rtsp(camera.mac, enabled=False)
    entity = WyzeCamera(SimpleNamespace(), camera, config_entry)
    assert await entity.stream_source() is None


@pytest.mark.asyncio
async def test_stream_source_is_none_for_a_different_camera(
    camera: SimpleNamespace,
) -> None:
    """Another camera's RTSP config in the same entry does not leak over."""
    config_entry = _config_entry_with_rtsp("11:22:33:44:55:66")
    entity = WyzeCamera(SimpleNamespace(), camera, config_entry)
    assert await entity.stream_source() is None


@pytest.mark.asyncio
async def test_stream_source_builds_plain_rtsp_url(camera: SimpleNamespace) -> None:
    """An insecure RTSP config builds a port-554 rtsp:// URL from the camera's IP."""
    config_entry = _config_entry_with_rtsp(camera.mac, secure=False)
    entity = WyzeCamera(SimpleNamespace(), camera, config_entry)
    assert await entity.stream_source() == "rtsp://wyze:hunter2@10.0.3.184:554/stream0"


@pytest.mark.asyncio
async def test_stream_source_builds_secure_rtsps_url(camera: SimpleNamespace) -> None:
    """A secure RTSP config builds a port-322 rtsps:// URL from the camera's IP."""
    config_entry = _config_entry_with_rtsp(camera.mac, secure=True)
    entity = WyzeCamera(SimpleNamespace(), camera, config_entry)
    assert await entity.stream_source() == "rtsps://wyze:hunter2@10.0.3.184:322/stream0"


@pytest.mark.asyncio
async def test_stream_source_percent_encodes_special_characters(
    camera: SimpleNamespace,
) -> None:
    """Credentials with URL-special characters (@, !, ^) are percent-encoded.

    Real RTSP passwords generated by the Wyze app can contain these
    characters -- a naive f-string would misparse the URL at an
    embedded unescaped '@'.
    """
    config_entry = _config_entry_with_rtsp(
        camera.mac, password="p@ss!w^rd", secure=True
    )
    entity = WyzeCamera(SimpleNamespace(), camera, config_entry)
    source = await entity.stream_source()
    assert source == "rtsps://wyze:p%40ss%21w%5Erd@10.0.3.184:322/stream0"


def test_use_stream_for_stills_is_always_true(entity: WyzeCamera) -> None:
    """HA's native Stream engine (not the dead async_camera_image) backs stills."""
    assert entity.use_stream_for_stills is True
